# Generated by Django 6.0.1 on 2026-02-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_historique', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'historique")),
                ('statut', models.BooleanField(default=False, verbose_name='Statut')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ESPECE', 'Espèce'), ('MOBILE_MONEY', 'Mobile Money'), ('WAVE_MONEY', 'Wave Money')], max_length=20, verbose_name='Source')),
                ('statut', models.BooleanField(default=True, verbose_name='Statut')),
                ('reference', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Référence')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Commission')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('frais_impression', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Frais d'impression")),
                ('service_annexe', models.BooleanField(default=False, verbose_name="Service d'annexe")),
                ('frais_annexe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Frais d'annexe")),
                ('intitule_annexes', models.CharField(blank=True, choices=[('PAGE_DE_GARDE', 'Page de garde'), ('MISE_EN_FORME', 'Mise en forme'), ('COMPLET', 'Complet')], max_length=30, null=True, verbose_name='Annexes')),
                ('jeu_reduction', models.BooleanField(default=False, verbose_name='Jeu de réduction')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total')),
                ('reduction_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pourcentage de réduction')),
                ('montant_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant de la réduction')),
                ('reduction_grattee', models.BooleanField(default=False, verbose_name='Réduction grattée')),
                ('reduction_revealed', models.BooleanField(default=False, verbose_name='Réduction révélée')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
