# Generated by Django 6.0.1 on 2026-02-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_historique', models.DateTimeField(auto_now_add=True)),
                ('statut', models.BooleanField(default=False)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ESPECE', 'Espèce'), ('MOBILE_MONEY', 'Mobile Money'), ('WAVE_MONEY', 'Wave Money')], max_length=20)),
                ('statut', models.BooleanField(default=True)),
                ('reference', models.CharField(editable=False, max_length=100, unique=True)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_parrain', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('frais_impression', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_annexe', models.BooleanField(default=False)),
                ('frais_annexe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('intitule_annexes', models.CharField(blank=True, choices=[('PAGE_DE_GARDE', 'Page de garde'), ('MISE_EN_FORME', 'Mise en forme'), ('COMPLET', 'Complet')], max_length=30, null=True)),
                ('jeu_reduction', models.BooleanField(default=False)),
                ('reduction_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('montant_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reduction_grattee', models.BooleanField(default=False)),
                ('reduction_revealed', models.BooleanField(default=False)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
    ]
