# Generated by Django 6.0.1 on 2026-02-19 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Paiements', '0001_initial'),
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Utilisateurs.etudiant'),
        ),
        migrations.AddField(
            model_name='historiquepaiement',
            name='paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='Paiements.paiement'),
        ),
    ]
