# Generated by Django 6.0.1 on 2026-02-19 17:39

import Dossiers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(choices=[('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], default='2025-2026', max_length=20)),
            ],
            options={
                'verbose_name': 'Année Académique',
                'verbose_name_plural': 'Années Académiques',
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(default=False)),
                ('livraison', models.BooleanField(default=False)),
                ('support_pdf', models.FileField(blank=True, null=True, upload_to=Dossiers.models.memoire_upload_path)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_livraison', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('LICENCE 3', 'LICENCE 3'), ('MASTER 2', 'MASTER 2')], default='LICENCE 3', max_length=20)),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
            },
        ),
    ]
