# Generated by Django 6.0.1 on 2026-02-19 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dossiers', '0001_initial'),
        ('Paiements', '0001_initial'),
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utilisateurs.etudiant'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Paiements.paiement'),
        ),
    ]
