# Generated by Django 6.0.1 on 2026-02-19 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dossiers', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('etudiant', 'Etudiant'), ('collaborateur', 'Collaborateur')], max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('AUDIT ET CONTRÔLE DE GESTION', 'AUDIT ET CONTRÔLE DE GESTION'), ('ADMINISTRATION DES AFFAIRES', 'ADMINISTRATION DES AFFAIRES'), ('ANGLAIS ', 'ANGLAIS'), ('SCIENCE JURIDIQUE OPTION DROIT PRIVE', 'SCIENCE JURIDIQUE OPTION DROIT PRIVE'), ('SCIENCE JURIDIQUE OPTION DROIT PUBLIC', 'SCIENCE JURIDIQUE OPTION DROIT PUBLIC'), ('FINANCE BANQUE ASSURANCE', 'FINANCE BANQUE ASSURANCE'), ('FINANCE COMPTABILITE ET GESTION DES ENTREPRISES', 'FINANCE COMPTABILITE ET GESTION DES ENTREPRISES'), ('GENIE CIVIL OPTION BATIMENT', 'GENIE CIVIL OPTION BATIMENT'), ('GENIE CIVIL OPTION TRAVAUX PUBLIC', 'GENIE CIVIL OPTION TRAVAUX PUBLIC'), ('GESTION DES RESSOURCES HUMAINE', 'GESTION DES RESSOURCES HUMAINE'), ('INFORMATIQUE OPTION GENIE LOGICIEL', 'INFORMATIQUE OPTION GENIE LOGICIEL'), ('LETTRES MODERNES', 'LETTRES MODERNES'), ('MARKETING MANAGEMENT', 'MARKETING MANAGEMENT'), ('MINE GEOLOGIE ET PETRÔLE', 'MINE GEOLOGIE ET PETRÔLE'), ('RESEAUX INFORMATIQUE ET TELECOMMUNICATION', 'RESEAUX INFORMATIQUE ET TELECOMMUNICATION'), ('SCIENCE ECONOMIQUE OPTION ECONOMIE', 'SCIENCE ECONOMIQUE OPTION ECONOMIE'), ('SCIENCE ECONOMIQUE OPTION GESTION', 'SCIENCE ECONOMIQUE OPTION GESTION'), ("SCIENCE DE L'INFORMATION ET DE LA COMMUNICATION", " SCIENCE DE L'INFORMATION ET DE LA COMMUNICATION"), ('SOCIOLOGIE ET ETHNOLOGIE', 'SOCIOLOGIE ET ETHNOLOGIE'), ('TOURISME HÔTELERIE', 'TOURISME HÔTELERIE'), ('TRANSPORT LOGISTIQUE ', 'TRANSPORT LOGISTIQUE')], max_length=100, unique=True)),
                ('abreviation', models.CharField(blank=True, default='IIPEA', max_length=10, null=True)),
                ('cycle', models.CharField(blank=True, choices=[('UNIVERSITAIRE', 'UNIVERSITAIRE'), ('PROFESSIONNEL', 'PROFESSIONNEL')], default='UNIVERSITAIRE', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('code_parainage', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_inscription_collaborateur', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Collaborateur',
                'verbose_name_plural': 'Collaborateurs',
            },
            bases=('Utilisateurs.utilisateur',),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True)),
                ('theme_memoire', models.CharField(max_length=255)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dossiers.anneeacademique')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utilisateurs.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dossiers.niveau')),
                ('parrain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Utilisateurs.collaborateur')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
            },
            bases=('Utilisateurs.utilisateur',),
        ),
    ]
